# Generated by Django 5.2 on 2025-05-20 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_photogallery_uploadfiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='photogallery',
            name='date',
            field=models.TextField(blank=True, max_length=50),
        ),
    ]
