# Generated by Django 5.1.7 on 2025-03-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='description',
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
