# Generated by Django 5.1.7 on 2025-03-21 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0003_contact_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
